name: Java Push

on:
  push:
    branches: 
    - main
    tags:
    - 0.*
    - 1.*
    - 2.*
  pull_request:
    branches: 
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'
    - name: Cache .m2
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build and Test
      run: mvn --batch-mode --update-snapshots clean verify

